image: tmaier/docker-compose:latest

stages:
    - build
    - test
    
services:
    - docker:dind

before_script:
    - docker info
    - docker-compose --version

build:
    stage: build
    tags:
        - docker
    script:
        - docker-compose build

test:
    stage: test
    script:
        - docker-compose run server yarn test --forceExit
        - docker-compose run server yarn test:e2e --forceExit