FROM node:10-alpine AS alpine

# Create app directory
WORKDIR /

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json .
RUN yarn 
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
# RUN ls -al
# RUN yarn seed; exit 0

EXPOSE 5000

CMD [ "yarn", "start:dev" ]
